@server_host = http://localhost:5050

###
GET {{server_host}}

###
GET {{server_host}}/test-stream

###
POST {{server_host}}/test-send
Content-Type: application/json

{
    "command": "How many devices are in the room"
}

###
POST {{server_host}}/test-loop
Content-Type: application/json

{
    "command": "How many devices are in the room"
}

###
POST {{server_host}}/test-loop
Content-Type: application/json

{
    "command": "It's a little bit cold in the living room"
}